### ISSUE TITLE
TypeError: Cannot set property 'flags' of undefined

### ISSUE THREAD

**Issue by himanshu-singh1995** [winstonjs/winston-transport#48]
Stack Trace:
```
ERROR	Unhandled Promise Rejection
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "TypeError: Cannot set property 'flags' of undefined",
    "stack": [
        "Runtime.UnhandledPromiseRejection: TypeError: Cannot set property 'flags' of undefined",
        "    at process.on (/var/runtime/index.js:29:13)",
        "    at process.emit (events.js:198:13)",
        "    at process.EventEmitter.emit (domain.js:448:20)",
        "    at emitPromiseRejectionWarnings (internal/process/promises.js:119:20)",
        "    at process._tickCallback (internal/process/next_tick.js:69:34)"
    ],
    "reason": {
        "errorType": "TypeError",
        "errorMessage": "Cannot set property 'flags' of undefined",
        "stack": [
            "TypeError: Cannot set property 'flags' of undefined",
            "    at URL.onParseComplete (internal/url.js:224:13)",
            "    at URL.set [as href] (internal/url.js:443:7)",
            "    at _clone (/opt/nodejs/node_modules/clone/clone.js:162:16)",
            "    at _clone (/opt/nodejs/node_modules/clone/clone.js:162:18)",
            "    at _clone (/opt/nodejs/node_modules/clone/clone.js:175:25)",
            "    at clone (/opt/nodejs/node_modules/clone/clone.js:202:10)",
            "    at validateMetadata (/opt/nodejs/node_modules/winston-loggly-bulk/lib/winston-loggly.js:104:12)",
            "    at exports.Loggly.Loggly.log (/opt/nodejs/node_modules/winston-loggly-bulk/lib/winston-loggly.js:118:19)",
            "    at exports.Loggly._write (/opt/nodejs/node_modules/winston-transport/index.js:81:19)",
            "    at doWrite (/opt/nodejs/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:428:64)"
        ]
    },
    "promise": {}
}
```

Dependencies in package.json
```
"dependencies": {
    "winston": "^3.2.1",
    "winston-loggly-bulk": "^3.0.1"
  },
```
Node Version: v10.16.0

I am using Loggly in AWS Lambda function. Node Modules are packed inside a lambda layer.  I am getting the above error about 20% times when the lambda function is executed.
Lambda Code: 
```
const winston = require('winston');
const { Loggly } = require('winston-loggly-bulk');

const getLogger = (mode, token, tag, subtag) => {
  const myFormat = winston.format.printf(info => `${info.timestamp} :${info.level.toUpperCase()}: [${info.label}] ${info.message}`);

  const logger = winston.createLogger({
    level: 'info',
    format: winston.format.combine(
      winston.format.label({ label: `${mode} : ${tag} : ${subtag}` }),
      winston.format.timestamp(),
      winston.format.splat(),
      winston.format.simple(),
      myFormat,
    ),
    transports: [
      // - Write to all logs with level `info` and below to `combined.log`
      // - Write all logs error (and below) to `error.log`.
      // new winston.transports.File({ filename: '../../logs/error.log', level: 'error' }),
      // new winston.transports.File({ filename: '../../logs/combined.log' })
    ],
  });

  logger.add(new Loggly({
    token,
    subdomain: '101commerce',
    tags: [mode, tag],
    json: true,
  }));

  logger.add(new winston.transports.Console({
    format: winston.format.combine(
      winston.format.label({ label: `${mode} : ${tag} : ${subtag}` }),
      winston.format.timestamp(),
      winston.format.splat(),
      winston.format.simple(),
      myFormat,
    ),
  }));

  return logger;
};
const LOGGLY_TOKEN = TOKEN
const logger = getLogger('development', LOGGLY_TOKEN, 'ultron', 'sub tag');
exports.handler = async function(event) {
// logic goes here
}
```

**Comment by himanshu-singh1995** [comment]
I accidentally sent an URL object while logging.
