### ISSUE TITLE
Error using sample to create new transport

### ISSUE THREAD

**Issue by lucky-lou** [winstonjs/winston-transport#7]
Not sure how this is supposed to work based on the limited example. Copped and pasted the example and I get this error. Using Winston 3.0.0-rc1

`C:\projects\STAR-CLASS\API\node_modules\winston-transport\legacy.js:17
    throw new Error('Invalid transport, must be an object with a log method.');
    ^

Error: Invalid transport, must be an object with a log method.
    at new LegacyTransportStream (C:\projects\STAR-CLASS\API\node_modules\winston-transport\legacy.js:17:11)
    at DerivedLogger.add (C:\projects\STAR-CLASS\API\node_modules\winston\lib\winston\logger.js:277:7)
    at Object.winston.(anonymous function) [as add] (C:\projects\STAR-CLASS\API\node_modules\winston\lib\winston.js:84:34)
    at Object.<anonymous> (C:\projects\STAR-CLASS\API\app\Strategies\logging.js:10:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)`

My code file:

```
const Transport = require('winston-transport');
const util = require('util');

//
// Inherit from `winston-transport` so you can take advantage
// of the base functionality and `.exceptions.handle()`.
//
module.exports = class OracleWinstonTransport extends Transport {
  constructor(opts) {
    super(opts);

    //
    // Consume any custom options here. e.g.:
    // - Connection information for databases
    // - Authentication information for APIs (e.g. loggly, papertrail, 
    //   logentries, etc.).
    //
  }

  log(info, callback) {
    setImmediate(function () {
      this.emit('logged', info);
    });

    // Perform the writing to the remote service

    callback();
  }
};
```

**Comment by indexzero** [comment]
Thanks for reporting @lucky-lou. Verified this is fixed by adding an example to `winston` itself with the same example code: https://github.com/winstonjs/winston/commit/fe9dcc9845a1b35c115c516728ea6bfed0570225
